<?php
 class TXT extends BaseObject
{
 public static $TXT_RAPORT = array("VENITURI_AFERENTE_COSTULUI_PRODUCTIEI_IN_CURS_DE_EXECUTIE" => "Venituri aferente costului productiei in curs de executie",
	"VENITURI_DIN_PRODUCTIA_DE_IMOBILIZARI" => "Venituri din productia de imobilizari",
	"VENITURI_DIN_DESPAGUBIRI_AMENZI_SI_PENALITATI" => "Venituri din despagubiri, amenzi si penalitati",
	"VENITURI_DIN_DONATII_PRIMITE" => "Venituri din donatii primite",
	"VENITURI_DIN_VANZAREA_ACTIVELOR_SI_ALTE_OPERATII_DE_CAPITAL" => "Venituri din vanzarea activelor si alte operatii de capital",
	"VENITURI_DIN_SUBVENTII_PENTRU_INVESTITII" => "Venituri din subventii pentru investitii",
	"ALTE_VENITURI_OCAZIONALE_DIN_EXPLOATARE" => "Alte venituri ocazionale din exploatare",
	"ALTE_VENITURI_DIN_EXPLOATARE" => "Alte venituri din exploatare",
	"CHELTUIELI_MATERIALE" => "Cheltuieli materiale",
	"CHELTUIELI_CU_SERVICII_PRESTATE_DE_TERTI" => "Cheltuieli cu servicii prestate de terti",
	"CHELTUIELI_DE_PERSONAL" => "Cheltuieli de personal",
	"SUBVENTII_PRIMITE_PENTRU_CHELTUIELI_DE_EXPLOATARE" => "Subventii primite pentru cheltuieli de exploatare",
	"VENITURI_FINANCIARE" => "Venituri financiare",
	"VENITURI_DIN_DOBANZI" => "Venituri din dobanzi",
	"VENITURI_DIN_DIFERENTE_DE_CURS_VALUTAR" => "Venituri din diferente de curs valutar",
	"VENITURI_DIN_SCONTURI_OBTINUTE" => "Venituri din sconturi obtinute",
	"ALTE_VENITURI_FINANCIARE" => "Alte venituri financiare",
	"CHELTUIELI_FINANCIARE" => "Cheltuieli financiare",
	"CHELTUIELI_PRIVIND_DOBANZILE" => "Cheltuieli privind dobanzile",
	"CHELTUIELI_DIN_DIFERENTE_DE_CURS_VALUTAR" => "Cheltuieli din diferente de curs valutar ",
	"CHELTUIELI_PRIVIND_SCONTURILE_ACORDATE" => "Cheltuieli privind sconturile acordate ",
	"ALTE_CHELTUIELI_FINANCIARE" => "Alte cheltuieli financiare",
	"PROFIT_DIN_ACTIVITATEA_FINANCIARA" => "Profit din activitatea financiara",
	"ALTE_CHELTUIELI_DE_EXPLOATARE" => "Alte cheltuieli de exploatare",
	"CHELTUIELI_CU_ALTE_IMPOZITE_TAXE_SI_VARSAMINTE_ASIMILATE" => "Cheltuieli cu alte impozite, taxe si varsaminte asimilate",
	"CHELTUIELI_CU_PROTECTIA_MEDIULUI_INCONJURATOR" => "Cheltuieli cu protectia mediului inconjurator",
	"DESPAGUBIRI_AMENZI_SI_PENALITATI" => "Despagubiri, amenzi si penalitati",
	"DONATII_ACORDATE" => "Donatii acordate",
	"CHELTUIELI_PRIVIND_ACTIVELE_CEDATE_SI_ALTE_OPERATII_DE_CAPITAL" => "Cheltuieli privind activele cedate si alte operatii de capital",
	"ALTE_CHELTUIELI_OCAZIONALE_DE_EXPLOATARE" => "Alte cheltuieli ocazionale de exploatare",
	"CHELTUIELI_CU_AMORTIZAREA_AJUSTARI_DE_VALOARE_SI_PROVIZIOANELE" => "Cheltuieli cu amortizarea, ajustari de valoare si provizioanele ",
	"TOTAL_VENITURI_DIN_EXPLOATARE" => "Total venituri din exploatare",
	"TOTAL_CHELTUIELI_DE_EXPLOATARE" => "Total cheltuieli de exploatare",
	"PROFIT_DIN_EXPLOATARE" => "Profit din  exploatare",
	"VENITURI_EXTRAORDINARE" => "Venituri extraordinare",
	"CHELTUIELI_EXTRAORDINARE" => "Cheltuieli extraordinare",
	"PROFIT_DIN_ACTIVITATEA_EXTRAORDINARA" => "Profit din activitatea extraordinara",
	"VENITURI_TOTALE" => "Venituri totale",
	"CHELTUIELI_TOTALE_INAINTE_IMPOZITARE" => "Cheltuieli totale inainte  de impozitare",
	"CHELTUIELI_TOTALE" => "Cheltuieli totale",
	"EBITDA" => "EBITDA",
	"EBIT" => "EBIT",
	"PROFIT_BRUT" => "Profit brut",
	"IMPOZIT_PE_PROFIT" => "Cheltuieli cu impozitul pe profit",
	"PROFIT_NET" => "Profit net",
	"PROFIT_AFERENT_ACTIVITATII_DE_BAZA" => "Profit aferent activitatii de baza",
	"CIFRA_DE_AFACERI" => "Cifra de afaceri",
	"VENITURI_DIN_VANZAREA_PRODUSELOR_FINITE" => "Venituri din vanzarea produselor finite",
	"VENITURI_DIN_VANZAREA_SEMIFABRICATELOR_SI_PRODUSELOR_REZIDUALE" => "Venituri din vanzarea semifabricatelor si produselor reziduale",
	"VENITURI_DIN_SERVICII_PRESTATE" => "Venituri din servicii prestate",
	"VENITURI_DIN_STUDII_SI_CERCETARI" => "Venituri din studii si cercetari",
	"VENITURI_DIN_REDEVENTE_LOCATII_DE_GESTIUNE_SI_CHIRII" => "Venituri din redevente, locatii de gestiune si chirii",
	"VENITURI_DIN_VANZAREA_MARFURILOR" => "Venituri din vanzarea marfurilor",
	"VENITURI_DIN_ACTIVITATI_DIVERSE" => "Venituri din activitati diverse",
	"REDUCERI_COMERCIALE_ACORDATE" => "Reduceri comerciale acordate",
	"VENITURI_DIN_SUBVENTII_DE_EXPLOATARE_AFERENTE_CIFREI_DE_AFACERI" => "Venituri din subventii de exploatare aferente cifrei de afaceri",
	"CHELTUIELI_CU_MATERIILE_PRIME" => "Cheltuieli cu materiile prime",
	"CHELTUIELI_CU_MATERIALELE_CONSUMABILE" => "Cheltuieli cu materialele consumabile",
	"CHELTUIELI_CU_OBIECTELE_DE_INVENTAR_MATERIALELE_NESTOCATE_SI_AMBALAJELE" => "Cheltuieli cu obiectele de inventar , materialele nestocate si ambalajele",
	"CHELTUIELI_PRIVIND_ENERGIA_SI_APA" => "Cheltuieli privind energia si apa",
	"CHELTUIELI_PRIVIND_ANIMALELE_SI_PASARILE" => "Cheltuieli privind animalele si pasarile",
	"CHELTUIELI_PRIVIND_MARFURILE" => "Cheltuieli privind marfurile",
	"REDUCERI_COMERCIALE_PRIMITE" => "Reduceri comerciale primite",
	"CHELTUIELI_CU_INTRETINEREA_SI_REPARATIILE" => "Cheltuieli cu intretinerea si reparatiile",
	"CHELTUIELI_CU_REDEVENTE_SI_CHIRII" => "Cheltuieli cu redevente si chirii",
	"CHELTUIELI_CU_PRIMELE_DE_ASIGURARE" => "Cheltuieli cu primele de asigurare",
	"CHELTUIELI_CU_STUDIILE_SI_CERCETARILE" => "Cheltuieli cu studiile si cercetarile",
	"CHELTUIELI_CU_COLABORATORII" => "Cheltuieli cu colaboratorii",
	"CHELTUIELI_PRIVIND_COMISIOANELE_SI_ONORARIILE" => "Cheltuieli privind comisioanele si onorariile",
	"CHELTUIELI_DE_PROTOCOL_RECLAMA_SI_PUBLICITATE" => "Cheltuieli de protocol, reclama si publicitate",
	"CHELTUIELI_CU_TRANSPORTUL_DE_BUNURI_SI_PERSONAL_DETASARI_TRASFERARI" => "Cheltuieli cu transportul de bunuri si personal, detasari, trasferari",
	"CHELTUIELI_POSTALE_SI_TAXE_DE_TELECOMUNICATII" => "Cheltuieli postale si taxe de telecomunicatii",
	"CHELTUIELI_CU_SERVICIILE_BANCARE" => "Cheltuieli cu serviciile bancare",
	"ALTE_CHELTUIELI_CU_SERVICIILE_EXECUTATE_DE_TERTI" => "Alte cheltuieli cu serviciile executate de terti",
	"CHELTUIELI_PENTRU_REALIZAREA_CIFREI_DE_AFACERI" => "Cheltuieli pentru realizarea cifrei de afaceri",
	"ACTIVE_CIRCULANTE" => "Active circulante",
	"DISPONIBIL_IN_CASERIE_SI_BANCA" => "Disponibil in caserie si banca",
	"INVESTITII_PE_TERMEN_SCURT" => "Investitii pe termen scurt",
	"CREANTE" => "Creante",
	"STOCURI" => "Stocuri",
	"CHELTUIELI_IN_AVANS" => "Cheltuieli in avans",
	"ACTIVE_IMOBILIZATE" => "Active imobilizate",
	"TOTAL_ACTIV" => "Total activ",
	"IMOBILIZARI_NECORPORALE" => "Imobilizari necorporale",
	"IMOBILIZARI_CORPORALE" => "Imobilizari corporale",
	"IMOBILIZARI_FINANCIARE" => "Imobilizari financiare",
	"CONTURI_LA_BANCI" => "Conturi la banci",
	"CASA" => "Casa",
	"ACREDITIVE_ALTE_VALORI_VIRAMENTE_INTERNE" => "Acreditive, alte valori, viramente interne",
	"AVANSURI_DE_TREZORERIE" => "Avansuri de trezorerie",
	"CLIENTI" => "Clienti",
	"FURNIZORI_DEBITORI" => "Furnizori debitori",
	"CREANTE_FATA_DE_PERSONALUL_ANGAJAT" => "Creante fata de personalul angajat",
	"CREANTE_FATA_DE_BUGETUL_DE_STAT" => "Creante fata de bugetul de stat",
	"SUBVENTII" => "Subventii",
	"CREANTE_FATA_DE_GRUP" => "Creante fata de grup",
	"ALTE_CREANTE" => "Alte creante",
	"DEBITORI_DIVERSI" => "Debitori diversi",
	"OPERATIUNI_IN_CURS_DE_CLARIFICARE_ACTIV" => "Operatiuni in curs de clarificare",
	"DECONTARI_IN_CADRUL_UNITATII_ACTIV" => "Decontari in cadrul unitatii",
	"DOBANZI_DE_PRIMIT" => "Dobanzi de primit",
	"AJUSTARI_PENTRU_DEPRECIEREA_CREANTELOR" => "Ajustari pentru deprecierea creantelor",
	"STOCURI_DE_MATERII_PRIME_SI_MATERIALE" => "Stocuri de materii prime si materiale",
	"STOCURI_IN_CURS_DE_APROVIZIONARE" => "Stocuri in curs de aprovizionare",
	"PRODUCTIA_IN_CURS_DE_EXECUTIE" => "Productia in curs de executie",
	"PRODUSE" => "Produse (semifabricate, finite, reziduale)",
	"STOCURI_AFLATE_LA_TERTI" => "Stocuri aflate la terti",
	"ANIMALE_SI_PASARI" => "Animale si pasari",
	"MARFURI" => "Marfuri",
	"AMBALAJE" => "Ambalaje",
	"AJUSTARI_PENTRU_DEPREC_STOCURILOR" => "Ajustari pentru deprec. stocurilor",
	"IMOBILIZARI_NECOROPRALE_VALOARE_DE_INTRARE" => "Imobilizari necoroprale - valoare de intrare",
	"AMORTIZARE_SI_AJUSTARI_IMOBILIZARI_NECORPORALE" => "Amortizare si ajustari privind imobilizarile necorporale",
	"TERENURI_SI_AMENAJARI_LA_TERENURI" => "Terenuri si amenajari la terenuri",
	"CONSTRUCTII" => "Constructii",
	"INSTALATII_TEHNICE_MIJ_TRANS" => "Instalatii tehnice, mij trans, animale si plantatii",
	"MOBILIER_BIROTICA_ECHIP_PROTECTIE" => "Mobilier, ap birotica, echip de protectie",
	"IMOBILIZARI_IN_CURS_DE_APROVIZIONARE_AVANSURI_ACORDATE" => "Imobilizari in curs de aprovizionare/executie, avansuri acordate",
	"AMORTIZARI_PRIVIND_IMOBILIZARILE_CORPORALE" => "Amortizari si ajustari privind imobilizarile corporale",
	"TOTAL_DATORII" => "Total datorii",
	"DATORII_PE_TERMEN_SCURT" => "DATORII pe termen scurt (scadenta sub 1 an)",
	"DATORII_FATA_DE_FURNIZORI" => "Datorii fata de furnizori",
	"CLIENTI_CREDITORI" => "Clienti creditori",
	"DATORII_FATA_DE_PERSONAL_PASIV" => "Datorii fata de personal",
	"DATORII_FATA_DE_BUGETUL_DE_STAT" => "Datorii fata de bugetul de stat",
	"DATORII_FATA_DE_GRUP" => "Datorii fata de grup",
	"DATORII_FATA_DE_ASOCIATI" => "Datorii fata de asociati si dividende de plata",
	"DATORII_FATA_DE_BANCI" => "Datorii fata de banci",
	"ALTE_DATORII" => "Alte datorii",
	"CREDITORI_DIVERSI" => "Creditori diversi",
	"DECONTARI_IN_CADRUL_UNITATII_PASIV" => "Decontari in cadrul unitatii",
	"OPERATIUNI_IN_CURS_DE_CLARIFICARE_PASIV" => "Operatiuni in curs de clarificare",
	"VARSAM_DE_EFECTUAT_PENTRU_INVESTITIILE_PE_T_S" => "Varsam. de efectuat pentru investitiile pe t.s.",
	"DATORII_PE_TERMEN_MEDIU_SI_LUNG" => "DATORII pe termen mediu si lung (scadenta peste 1 an)",
	"VENITURI_IN_AVANS" => "Venituri in avans",
	"SUBVENTII_PENTRU_INVESTITII" => "Subventii pentru investitii",
	"VENITURI_INREGISTRATE_IN_AVANS" => "Venituri inregistrate in avans",
	"FOND_COMERCIAL_NEGATIV" => "Fond comercial negativ",
	"PROVIZIOANE" => "Provizioane",
	"CAPITALURI_PROPRII" => "Capitaluri proprii",
	"CAPITAL_SI_REZERVE" => "Capital si rezerve",
	"REZULTAT_REPORTAT" => "Rezultatul reportat",
	"REZULTATUL_EXERCITIULUI" => "Rezultatul exercitiului",
	"ALTE_CASTIGURI_PASIV" => "Alte castiguri/pierderi din operatii de capital, actiuni proprii",
	"REPARTIZAREA_PROFITULUI" => "Repartizarea profitului",
	"TOTAL_PASIV" => "Total pasiv",	
	"PROFITABILITATE" => "Profitabilitate",
	"RATA_PROFITULUI_NET" => "<b>Rata profitului net =</b><br/>(Profit net / Cifra de afaceri )*100",
	"RATA_PROFITULUI_DIN_EXPLOATARE" => "<b>Rata profitului din exploatare =</b><br/>Profit din exploatare/Total venituri*100",
	"RATA_PROFITABILITATII_TOTALE" => "<b>Rata profitabilitatii totale =</b><br/>Profit net/Total venituri*100",
	"MARJA_EBITDA" => "<b>Marja EBITDA =</b><br/>EBITDA/Cifra de afaceri*100",
	"GRAD_DE_INDATORARE_TOTAL" => "<b>Grad de indatorare total =</b><br/>(Datorii peste un an + Datorii pana intr-un an) / Pasiv total*100",
	"GRAD_DE_INDATORARE_LA_TERMEN" => "<b>Grad de indatorare la termen =</b><br/> Datorii pe termen mai mare de un an / Pasiv Total*100",
	"GRAD_DE_INDATORARE_PE_TERMEN_SCURT" => "<b>Grad de indatorare pe termen scurt = </b><br/>Datorii pana la un an / Pasiv Total*100",
	"SOLVABILITATE" => "<b>Solvabilitate =</b><br/>Capitaluri proprii / (Datorii pe termen mai mare de un an + Datorii pana la un an) *100",
	"LICHIDITATEA_GENERALA" => "<b>Lichiditatea generala =</b><br/>Activ circulant/Datorii pe termen scurt",
	"LICHIDITATEA_IMEDIATA" => "<b>Lichiditatea imediata =</b><br/>(Activ circulant-Stocuri)/Datorii pe termen scurt",
	"ECHILIBRUL_FINANCIAR_PE_TERMEN_LUNG" => "<b>Echilibrul financiar pe termen lung =</b><br/>Active imobilizate/(Datorii pe termen lung+Capitaluri proprii)",
	"PERIOADA_DE_STOCARE" => "<b>Perioada de stocare =</b><br/>Stocuri/Cheltuieli materiale*nr. zile",
	"PERIOADA_INCASARE_CREANTE_CLIENTI" => "<b>Perioada de incasare a creantelor de la clienti =</b><br/>Clienti/Cifra de afaceri*nr. zile",
	"PERIOADA_PLATA_FURNIZORILOR" => "<b>Perioada de plata  a furnizorilor =</b><br/>Furnizori/Cheltuieli materiale*nr. zile"/*,
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",*/
	
 
 );
 
 public static $LABELS = array(
	"currency" => "RON",
	"percent" => "%",
	"days" => "zile",
	"points" => " ",
 );
 
 public static $MONTHS = array(1 => 'Ianuarie', 2 => 'Februarie', 3 => 'Martie', 4 => 'Aprilie', 5 => 'Mai', 6 => 'Iunie', 7 => 'Iulie', 8 => 'August', 9 => 'Septembrie', 10 => 'Octombrie', 11 => 'Noiembrie', 12 => 'Decembrie');
 
 }
 


 ?>